[build]
  publish = "public"
  command = "composer install && php artisan build"

[build.environment]
  PHP_VERSION = "8.2" # Ganti sesuai dengan versi PHP yang digunakan di aplikasi Anda

[[redirects]]
  from = "/*"
  to = "/index.php/:splat"
  status = 200
  force = true
